pipeline {
    agent any
    
    environment {
        DOCKER_PASSWORD = credentials("docker_password")
    }

    stages {
        stage('Compile') {
            steps {
                sh './gradlew clean compileJava'
            }
        }

        stage('Deploy Infrastructure') {
            steps {
                script {
                    // Acum că ai șters tot manual, comanda asta nu va mai da eroare de port
                    sh 'docker compose up -d mongo'
                    sh 'sleep 15'
                }
            }
        }

        stage('Verify & All Tests') {
            steps {
                sh './gradlew test' 
            }
        }
    }

    post {
        always {
            sh 'docker compose down'
        }
    }
}